#!/bin/bash

CURRENT_BRANCH=$(git branch --show-current)

if [[ $1 == '-h' || $1 == '--help' ]]; then
  echo 'Usage:'
  echo '  stash'
  echo '  stash -p'
  echo '  stash --pop'
  echo 'Explain:'
  echo '  Use within a git repository with changes that need to be stashed'
  echo '  The -p or --pop flag will pop the most recent stash associated with the current branch'
  exit
elif [[ $1 == '-p' || $1 == '--pop' ]]; then
  echo "Popping stash for branch $CURRENT_BRANCH"
  STASH=$(git stash list | grep "$CURRENT_BRANCH" | head -n 1 | cut -d ':' -f 1)
  git stash pop $STASH
  exit
fi

if [[ `git status --porcelain` ]]; then
  # stash existing changes
  git stash -m "WIP auto stashed via stash script"
else
  echo "No changes to stash..."
fi
