#!/bin/bash

###### 2 arguments
# 1- string (message / command / script that returns string)
# 2- the number to text the message to

DEFAULT_NUMBER=$PHONE
DEFAULT_MESSAGE='This has been a test of the Home Broadcast System'
NUMBER=''
MESSAGE=''

if [[ $1 == '-h' || $1 == '--help' ]]; then
  echo 'Usage:'
  echo '  text <message> <phone_number>'
  echo 'Examples:'
  echo '  text'
  echo '  text "Hello World" 1234567890'
  echo 'Arguments:'
  echo '  $1 - message (Can also be command or script that outputs a string)'
  echo '  $2 - phone_number (Number to send the message to)'
  exit
fi

if [[ -z $1 ]]; then
  echo "No message provided"
  MESSAGE=$DEFAULT_MESSAGE
else 
  MESSAGE=$1
fi
if [[ -z $2 ]]; then
  echo "No number provided"
  NUMBER=$DEFAULT_NUMBER
else
  NUMBER=$2
fi

osascript -e "tell application \"Messages\" to send \"$MESSAGE\" to buddy \"$NUMBER\""
